QUESTION_MAPPINGS = [
  {
    "id": "P1Q1",
    "phase": "P1",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "self_structure",
  },
  {
    "id": "P1Q2",
    "phase": "P1",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "self_decision",
  },
  {
    "id": "P1Q3",
    "phase": "P1",
    "traits": ["S", "N"],
    "options": [{"S": 1.0}, {"N": 1.0}],
    "signal": "self_information",
  },
  {
    "id": "P1Q4",
    "phase": "P1",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "self_energy",
  },
  {
    "id": "P1Q5",
    "phase": "P1",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "self_deadline",
  },
  {
    "id": "P1Q6",
    "phase": "P1",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "self_closure",
  },
  {
    "id": "P2Q1",
    "phase": "P2",
    "traits": ["T", "F", "S"],
    "options": [{"T": 0.75, "N": 0.25}, {"F": 1.0}, {"S": 1.0}],
    "signal": "natural_media_pull",
  },
  {
    "id": "P2Q2",
    "phase": "P2",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "free_time_energy",
  },
  {
    "id": "P2Q3",
    "phase": "P2",
    "traits": ["N", "S"],
    "options": [{"N": 1.0}, {"S": 1.0}],
    "signal": "topic_attraction",
  },
  {
    "id": "P2Q4",
    "phase": "P2",
    "traits": ["T", "N"],
    "options": [{"T": 1.0}, {"N": 1.0}],
    "signal": "rejection_pattern",
  },
  {
    "id": "P2Q5",
    "phase": "P2",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "activity_preference",
  },
  {
    "id": "P3Q1",
    "phase": "P3",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "social_recovery",
  },
  {
    "id": "P3Q2",
    "phase": "P3",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "actual_deadline",
  },
  {
    "id": "P3Q3",
    "phase": "P3",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "actual_decision",
  },
  {
    "id": "P3Q4",
    "phase": "P3",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "company_leadership",
  },
  {
    "id": "P3Q5",
    "phase": "P3",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "political_leadership",
  },
  {
    "id": "P4Q1",
    "phase": "P4",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "right_kind_instinct",
  },
  {
    "id": "P4Q2",
    "phase": "P4",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "truth_comfort_instinct",
  },
  {
    "id": "P4Q3",
    "phase": "P4",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "plan_flow_instinct",
  },
  {
    "id": "P4Q4",
    "phase": "P4",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "respect_love_instinct",
  },
  {
    "id": "P4Q5",
    "phase": "P4",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "alone_people_instinct",
  },
]

QUESTION_MAPPING_BY_ID = {item["id"]: item for item in QUESTION_MAPPINGS}
