QUESTION_MAPPINGS = [
  {
    "id": "P1Q1",
    "phase": "P1",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "self_structure",
  },
  {
    "id": "P1Q2",
    "phase": "P1",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "self_decision",
  },
  {
    "id": "P1Q3",
    "phase": "P1",
    "traits": ["S", "N"],
    "options": [{"S": 1.0}, {"N": 1.0}],
    "signal": "self_information",
  },
  {
    "id": "P1Q4",
    "phase": "P1",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "self_energy",
  },
  {
    "id": "P1Q5",
    "phase": "P1",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "self_deadline",
  },
  {
    "id": "P1Q6",
    "phase": "P1",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "self_closure",
  },
  {
    "id": "P2Q1",
    "phase": "P2",
    "traits": ["T", "F", "S"],
    "options": [{"T": 0.75, "N": 0.25}, {"F": 1.0}, {"S": 1.0}],
    "signal": "natural_media_pull",
  },
  {
    "id": "P2Q2",
    "phase": "P2",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "free_time_energy",
  },
  {
    "id": "P2Q3",
    "phase": "P2",
    "traits": ["N", "S"],
    "options": [{"N": 1.0}, {"S": 1.0}],
    "signal": "topic_attraction",
  },
  {
    "id": "P2Q4",
    "phase": "P2",
    "traits": ["T", "N"],
    "options": [{"T": 1.0}, {"N": 1.0}],
    "signal": "rejection_pattern",
  },
  {
    "id": "P2Q5",
    "phase": "P2",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "activity_preference",
  },
  {
    "id": "P3Q1",
    "phase": "P3",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "social_recovery",
  },
  {
    "id": "P3Q2",
    "phase": "P3",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "actual_deadline",
  },
  {
    "id": "P3Q3",
    "phase": "P3",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "actual_decision",
  },
  {
    "id": "P3Q4",
    "phase": "P3",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "company_leadership",
  },
  {
    "id": "P3Q5",
    "phase": "P3",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "political_leadership",
  },
  {
    "id": "P3Q6",
    "phase": "P3",
    "traits": ["F", "T", "I"],
    "options": [{"F": 0.8, "J": 0.2}, {"T": 0.8, "J": 0.2}, {"I": 0.6, "T": 0.4}],
    "behaviorOptions": [
      {"loyalty": 8, "betrayalSensitivity": 5, "forgiveness": 8, "impulseControl": 6},
      {"loyalty": 3, "betrayalSensitivity": 9, "forgiveness": 2, "impulseControl": 7},
      {"loyalty": 5, "betrayalSensitivity": 8, "forgiveness": 4, "impulseControl": 5},
    ],
    "signal": "trust_break_response",
  },
  {
    "id": "P3Q7",
    "phase": "P3",
    "traits": ["F", "J", "P"],
    "options": [{"F": 0.8, "J": 0.2}, {"J": 0.7, "T": 0.3}, {"P": 0.8, "I": 0.2}],
    "behaviorOptions": [
      {"loyalty": 9, "drive": 5, "slothRisk": 2, "impulseControl": 6},
      {"loyalty": 6, "drive": 8, "slothRisk": 2, "impulseControl": 8},
      {"loyalty": 2, "drive": 3, "slothRisk": 8, "impulseControl": 4},
    ],
    "signal": "loyalty_under_load",
  },
  {
    "id": "P3Q8",
    "phase": "P3",
    "traits": ["N", "T", "F"],
    "options": [{"N": 0.6, "T": 0.4}, {"T": 0.6, "F": 0.4}, {"F": 0.8, "I": 0.2}],
    "behaviorOptions": [
      {"envy": 2, "drive": 8, "impulseControl": 7},
      {"envy": 6, "drive": 9, "impulseControl": 5},
      {"envy": 8, "drive": 3, "impulseControl": 3},
    ],
    "signal": "comparison_response",
  },
  {
    "id": "P3Q9",
    "phase": "P3",
    "traits": ["J", "P", "T"],
    "options": [{"J": 0.9, "T": 0.1}, {"P": 0.9, "T": 0.1}, {"T": 0.7, "P": 0.3}],
    "behaviorOptions": [
      {"drive": 9, "slothRisk": 2, "impulseControl": 8},
      {"drive": 4, "slothRisk": 7, "impulseControl": 4},
      {"drive": 6, "slothRisk": 5, "impulseControl": 6},
    ],
    "signal": "boring_work_response",
  },
  {
    "id": "P3Q10",
    "phase": "P3",
    "traits": ["J", "P", "N"],
    "options": [{"J": 0.8, "F": 0.2}, {"P": 0.8, "F": 0.2}, {"N": 0.6, "P": 0.4}],
    "behaviorOptions": [
      {"loyalty": 9, "impulseControl": 9, "lustImpulse": 2, "drive": 7},
      {"loyalty": 3, "impulseControl": 3, "lustImpulse": 8, "drive": 4},
      {"loyalty": 6, "impulseControl": 7, "lustImpulse": 5, "drive": 5},
    ],
    "signal": "temptation_response",
  },
  {
    "id": "P4Q1",
    "phase": "P4",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "right_kind_instinct",
  },
  {
    "id": "P4Q2",
    "phase": "P4",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "truth_comfort_instinct",
  },
  {
    "id": "P4Q3",
    "phase": "P4",
    "traits": ["J", "P"],
    "options": [{"J": 1.0}, {"P": 1.0}],
    "signal": "plan_flow_instinct",
  },
  {
    "id": "P4Q4",
    "phase": "P4",
    "traits": ["T", "F"],
    "options": [{"T": 1.0}, {"F": 1.0}],
    "signal": "respect_love_instinct",
  },
  {
    "id": "P4Q5",
    "phase": "P4",
    "traits": ["I", "E"],
    "options": [{"I": 1.0}, {"E": 1.0}],
    "signal": "alone_people_instinct",
  },
]

QUESTION_MAPPING_BY_ID = {item["id"]: item for item in QUESTION_MAPPINGS}
